---
# tasks file for docker

- name: load OS specific variables (see ../vars/*)
  include_vars: "{{ ansible_os_family }}.yml"

- name: install docker packages
  action: "{{ ansible_pkg_mgr }} pkg=docker state=latest"

- name: "Enable docker at startup and make sure it is running"
  service: name=docker state=started enabled=yes
